### ISSUE TITLE
Set background-color in CSS

### ISSUE THREAD

**Issue by jplatte** [mgattozzi/mgattozzi.github.io#2]
Your CSS has a color for all of the text on the page, but the body background-color is the default. My browser doesn't have the usual color defaults (it's a setting in Firefox, under Content -> Colors) so I can't read anything without changing the CSS. It would make sense if your CSS would set `body { background-color: #fff; }`, because it also sets the text color. Here's your current article in my FF setup:

![bildschirmfoto am 2016-09-28 um 01 12 43](https://cloud.githubusercontent.com/assets/951129/18895298/d8de9686-8518-11e6-8f0f-91766f02fa96.png)

**Comment by mgattozzi** [comment]
Thanks for taking the time letting me know. I think I'm going to have to muck around with the CSS settings myself since it looks like no updates have been made to https://github.com/ageitgey/amplify in quite some time. If I can find the time I'll definitely fix it. Particularly swamped with classes and work at this time though.

**Comment by jplatte** [comment]
Fixed in amplify: https://github.com/ageitgey/amplify/issues/17 :)

**Comment by mgattozzi** [comment]
You're the best! I'll make sure to update the styling then close out the issue!

**Comment by mgattozzi** [comment]
I just made the update to the site. Feel free to reopen the issue if the problem persists!
